### ISSUE TITLE
provide a release compatible with Ubuntu Jammy Jellyfish

### ISSUE THREAD

**Issue by metskem** [cloudfoundry-community/nginx-release#22]
Stemcells based on Ubuntu Jammy (22.04) are currently in Alpha.
We tried to compile nginx-release with this stemcell, but the compile fails, see attached file
[nginx.log](https://github.com/cloudfoundry-community/nginx-release/files/7944268/nginx.log)
 for the logs.
Can you provide a Jammy compatible nginx-release?

**Comment by cunnie** [comment]
Hi @metskem : Thanks for the tip, and I want to compliment you on the speed with which you noticed the publication of the Jammy stemcells.

I'll try to update the release over the course of the next few days..

**Comment by benjaminguttmann-avtq** [comment]
Okay :D that is the same issue I see when trying to deploy the prometheus-boshrelease. Tried to bump a couple of things already but nothing worked for me so far. @cunnie maybe your solution will 'inspire' me on how to fix the issue for the prometheus bosh-release :D

**Comment by benjaminguttmann-avtq** [comment]
Little update from my side, bumping nginx to v1.21.6 fixed the problems with compilation for me.

**Comment by cunnie** [comment]
@metskem 

I've published a new release, 1.21.6, but this **will not fix your compilation issue**!

I've looked at your logs, and whichever nginx release you're using, you're not using the Community version: the release you're using is compiling nginx-1.20.1, and the Community has **never** released on the stable (1.20) branch of nginx; we've only released on the mainline branch (1.19, 1.21).

In fact, I tested the Community's previous release (1.21.3), and it compiles fine on Jammy, which makes sense because according to the [changelog](https://nginx.org/en/CHANGES), OpenSSL 3 support has been included since 1.21.2.

**Comment by metskem** [comment]
Thanks for the update.
The compile error occurs while compiling the current capi release, which has an nginx package, see https://github.com/cloudfoundry/capi-release/tree/main/packages/nginx .
I will file an issue there.
